### ISSUE TITLE
What about Firefox?

### ISSUE THREAD

**Issue by inson1** [DeGrandis/Youtube-rss-chrome-plugin#11]

**Comment by DeGrandis** [comment]
it can be added manually to firefox.

**Comment by inson1** [comment]
@DeGrandis so why dont you add it to the firefox store?

**Comment by DeGrandis** [comment]
the project is currently nonfunctional since youtube changed its frontend code.  the user base on firefox is not enough to warrant the effort of putting it on there with updates.

**Comment by inson1** [comment]
@DeGrandis And are you gonna fix it or do you at least set licence so someone else could?

**Comment by inson1** [comment]
@DeGrandis And btw the issues were for if you want to fix it and get it better
