### ISSUE TITLE
"Copied to clipboard" message redesign

### ISSUE THREAD

**Issue by ftphikari** [DeGrandis/Youtube-rss-chrome-plugin#5]
"Copied to clipboard" message should be redesigned to fit current Youtube style better, like this popup
![image](https://user-images.githubusercontent.com/92269215/147853883-a0dc2078-d86e-4e43-80a9-59331769e412.png)

I reckon it's not that hard, is it?

**Comment by DeGrandis** [comment]
What suggested style do you mean?  The current popup looks similar enough in my oppinion.  I am open to hearing out what you mean though.

**Comment by ftphikari** [comment]
The current popup is similar, except it's not a popup, it shifts the layout above it. The actual popup is trivial to do with `position: relative;` or something, and it would look much more fitting, you know what I mean?
